### ISSUE TITLE
Loading other aggregates from inside aggregate root

### ISSUE THREAD

**Issue by asgerhallas** [d60/Cirqus#34]
As we discussed, it might be an idea to remove the Load methods from inside aggregate roots. There were four arguments for it, as far as I remember, but I can only remember three of them :)

1. It would make dependencies to other aggregate roots and coordination between them explicit in the application services where the scope of the transaction is also easily seen. 

2. If loading in the aggregate root seems neccessary (eg some action must - dependent on some business logic - result in an action on another aggregate root), one could inject a repository in the root's method, or a domain event handler could just as easily react to the emitted events, making action -> reaction clear.

3. It would simplify testing of the domain models, as IUnitOfWork would become a simpler interface to implement. And IUnitOfWork would live up to its name.

**Comment by mookid8000** [comment]
I'll close this one for now - all AR loading operations are still available in aggregate roots - if you don't like this, just don't use them.
