### ISSUE TITLE
Letting go of the type parameter on TestContext.Save()

### ISSUE THREAD

**Issue by asgerhallas** [d60/Cirqus#36]
I'd like to be able to do something like this,

        public void Given(params IEnumerable<DomainEvent>[] events)
        {
            foreach (var domainEvent in events.SelectMany(x => x))
            {
                context.Save((dynamic)domainEvent);
            }
        }

but without dynamic. 

Would it be an idea to relax the Save method signature, or have non-generic overloads, that enables that? And also enables - the thing you talked about - being able to emit events that do not originate from an aggregate (albeit not the actual feature, just removing hindrance)

**Comment by asgerhallas** [comment]
I'll close this one then. We can discuss it some other day :)

**Comment by mookid8000** [comment]
:+1:
