### ISSUE TITLE
Type argument constraint to AggregateRoot

### ISSUE THREAD

**Issue by asgerhallas** [d60/Cirqus#40]
I see that this has been changed a little while back:

     -        TAggregateRoot TryLoad<TAggregateRoot>(string aggregateRootId) where TAggregateRoot : AggregateRoot, new();
        
     +        TAggregateRoot TryLoad<TAggregateRoot>(string aggregateRootId) where TAggregateRoot : class;

Is there any reason not to constrain this to AggregateRoot as opposed to just class? This spreads out down to repositories, and I have some excessive casting in some of my decorators because of it.

**Comment by mookid8000** [comment]
There's no type constraint because you must be able to do this:

    var instance = context.Load<ICanDoStuff>(someId);
    instance.DoStuff();

Obviously, `Create` has a type constraint because the created instance must be of a concrete aggregate root type, but `Load` and `TryLoad` should support polymorphy.

**Comment by mookid8000** [comment]
BAM!!!11

(the sound of an issue being almost immediately closed)

**Comment by asgerhallas** [comment]
Oh yes, you're right. I totally forgot about that :)

**Comment by mookid8000** [comment]
You're right that I'm right. And you're right, you forgot about that.

**Comment by asgerhallas** [comment]
I'll keep 'em coming! :-p

**Comment by mhertis** [comment]
protected TAggregateRoot TryLoad<TAggregateRoot>(string aggregateRootId) where TAggregateRoot : AggregateRoot, new()

Wondering why is there new() constraint? It prevents us to make our base class abstract.

**Comment by mookid8000** [comment]
good find, @mhertis , that sounds like an oversight - can't see why `TryLoad` should have type constraints when `Load` should not.
