### ISSUE TITLE
Transfer metadata to events before emit

### ISSUE THREAD

**Issue by asgerhallas** [d60/Cirqus#45]
Metadata from commands are transferred to events and can then be used in handlers on views. But they cannot be used in apply methods on roots, as they have not been transferred yet, at the time. Would there be any problems in moving the transfer of metadata into the aggregate root before the applies are called?

**Comment by mookid8000** [comment]
no

**Comment by mookid8000** [comment]
![no](http://images.sodahead.com/polls/003660559/451284385_Annoying_no_gif_answer_2_xlarge.gif)

**Comment by mookid8000** [comment]
![](http://www.reactiongifs.com/wp-content/uploads/2013/08/no-answer.gif)

**Comment by asgerhallas** [comment]
But why did you close it then? :-O

**Comment by mookid8000** [comment]
sorry

**Comment by asgerhallas** [comment]
You're soooo sending mixed signal :)

**Comment by asgerhallas** [comment]
Are you still using the ability to Load in an apply method of an aggregate root, or is it just in the emitting method, you use it?

**Comment by asgerhallas** [comment]
@mookid8000 if you do, I need to "flow" the metadata further down, and I'll fix that if you need it :)

**Comment by mookid8000** [comment]
I do - but the loaded root cannot `Emit` when it's loaded from an `Apply`

**Comment by asgerhallas** [comment]
Oh. All good then :)
