### ISSUE TITLE
Rollbacking event writes

### ISSUE THREAD

**Issue by rasmuseo** [d60/Cirqus#47]
Hi, we are using Cirqus as an event repository (in SQL Server) but our views are hand-crafted (handling the dispatched event via a custom `IEventDispatcher`) in RavenDb.

Problem comes when for some reason one of the handlers for the dispatched event fails. In that situation the event has been commited to the store, but the "views" are not in sync with what in the event store. In our case, that becomes a problem.

What would be the best way to approach this situation and "get rid of" the mismatch?
Note: enlisting the whole operation inside a distributed transaction (via `TransactionScope`) is not a possibility.

We are using _0.41.0_ and we'd like to avoid updating if possible.

**Comment by mookid8000** [comment]
hi @rasmuseo , thanks for your question! could you maybe post it on StackOverflow and tag it with "cirqus" - then I promise I will give you a quick and thorough answer :)

thanks!

**Comment by rasmuseo** [comment]
It's added to StackOverflow now - But I didn't have enough reputation to add the 'cirqus' tag (sigh). Its called 'Cirqus - Rollbacking Events' and tagged with event-handling and transaction.

I would appriciate it if you would take a look at it.

**Comment by mookid8000** [comment]
I added the 'cirqus' tag and wrote you [an answer](http://stackoverflow.com/a/29033681/6560)
