### ISSUE TITLE
Improvements for the TsClient

### ISSUE THREAD

**Issue by asgerhallas** [d60/Cirqus#49]
@larsudengaard and I was talking about improving the TsClient for:

1. Making it possible to select types by some sort of "in project" configuration class
2. Making special conversion of given types, like Id<T> to a string
3. Support TypeScript interfaces for Views too

The default command line tool could still work as today. 

Do you have any thoughts on that?

**Comment by larsudengaard** [comment]
I on it! :-) I will make a pull-request, when it is done.

**Comment by larsudengaard** [comment]
I created a separate project for this. It is located here: https://github.com/larsudengaard/Cirqus.TypeScript

**Comment by mookid8000** [comment]
:+1:
