### ISSUE TITLE
Inheritance of AggregateRoots and Emit issue

### ISSUE THREAD

**Issue by h3ko** [d60/Cirqus#50]
Hello,

First of all, Cirqus is great and thank you for dev it! We use it a lot and recently came across an issue with inheritance. Is there any reason why aggregates should not emit events from aggregates extending them?

Example:

Base aggregate & event:
   public class Device : AggregateRoot {}
   public class DeviceChanged : DomainEvent<Device>

Two classes extending the base aggregate:
   public class SpecialDeviceA : Device {}
   public class SpecialDeviceB : Device {}

Although SpecialDeviceA is Device, if I create a SpecialDeviceA and call some method implemented by Device (base) emitting DeviceChanged event I get:
System.InvalidOperationException: Attempted to emit event “DeviceChanged”  which is owned by “Device” from aggregate root of type “SpecialDeviceA”.

For now I fixed it with checking if Agg type is assignable from X (and only the exact type of X) in the d60.Cirqus.Aggregates.AggregateRoot.cs, line 81:

From: if (typeof(TAggregateRoot) != GetType())
To: if(!typeof(TAggregateRoot).IsAssignableFrom(GetType()))

Aggregate tests still pass :)

Is this ok? As we (and probably others too) use inheritance with Aggregates (nature of our domain), maybe Cirqus could enable this by default?

Kind regards,
Martin

**Comment by mookid8000** [comment]
Oh, that is definitely ok :+1:  if you submit a PR, I'd be happy to merge it :)

**Comment by asgerhallas** [comment]
Should the Owner meta data of the event be set to the emitting type instead of the owning type then? I believe it's used when instantiating roots and that needs to be the concrete type.

**Comment by mookid8000** [comment]
Yes, it should be the concrete type of the aggregate root, no matter if it's inhertited off of some kind of base class.

**Comment by h3ko** [comment]
Doesn't this work by default?

It gets type of the current instance - if the instance is for example SpecialDeviceA (extends Device) type is SpecialDeviceA and not the base class Device.

 e.Meta.TakeFromAttributes(GetType());

**Comment by asgerhallas** [comment]
I'm thinking of this line in RealUnitOfWork.AddEmittedEvent<TAggregateRoot>():

    e.Meta[DomainEvent.MetadataKeys.Owner] = _typeNameMapper.GetName(typeof (TAggregateRoot));

It takes the type of the owner defined by the event - in this case the base type Device. That means that the DefaultAggregateRootRepository.Get() will try to create an instance of the base type here:

    var aggregateRootTypeName = e.Meta[DomainEvent.MetadataKeys.Owner];
    var aggregateRootType = _domainTypeNameMapper.GetType(aggregateRootTypeName);
    aggregateRoot = CreateNewAggregateRootInstance(aggregateRootType, aggregateRootId, unitOfWork);

So I AddEmittedEvent ought to by changed, I believe, to make it work.

**Comment by asgerhallas** [comment]
As an aside, I guess Emitter would be a better name for the metadata key. But I guess that'll break some running systems :)

**Comment by mat3y** [comment]
I implemented this with suggested emitter metadata and it seems to work.

In AggregateRoot
```
            e.Meta[DomainEvent.MetadataKeys.Emitter] = GetType().AssemblyQualifiedName;

```
In RealUnitOfWork
```
            var emitterType = Type.GetType(e.Meta[DomainEvent.MetadataKeys.Emitter]);
            e.Meta[DomainEvent.MetadataKeys.Owner] = _typeNameMapper.GetName(emitterType);

```

Now the problem is that I cannot get type of concrete aggregate root in CirqusTestsHarness.
```
     void Emit<T>(string id, DomainEvent<T> @event) where T : AggregateRoot
        {
            @event.Meta[DomainEvent.MetadataKeys.AggregateRootId] = id;
            ..
        }
```

Any idea?

**Comment by mhertis** [comment]
Eventually, I came up with some kind of solution. Please check out [latest commits](https://github.com/mhertis/Cirqus/commits/master).

**Comment by asgerhallas** [comment]
I see the problem in the test harness, I think your solution is the right one. But I have a few comments on the UnitOfWork... I'll leave them in the commits :)

**Comment by asgerhallas** [comment]
I said a few, but in reality just one.

It's a tough one with the TestContext and the harness. I believe that emitted events should not have an owning type at all, but that might be a discussion for another day :)

**Comment by mhertis** [comment]
[Take 2](https://github.com/mhertis/Cirqus/commit/3370774bab223a2ddf2efa4d962497a1b0c1e3a3), this time without Emitter :)
