### ISSUE TITLE
View / Projections

### ISSUE THREAD

**Issue by mpaul31** [d60/Cirqus#53]
i have not fully dove into this yet but is their any examples out there that show more in-depth usage of the view manager / projections? does the framework handle idempotent such that the view will only receive an event once?

**Comment by mookid8000** [comment]
We haven't gotten around to building more detailed examples, but I can tell you that the view managers are pretty strict about handling each event exactly once, and always strictly in order.

Moreover - if you haven't discovered this already - the views automatically catch up in the background, so if you need to replay a view, you can just wipe the data and the stored position for that view, and then it will automatically be rebuilt.

**Comment by mpaul31** [comment]
ok thanks i'll give it a go.
