### ISSUE TITLE
CurrentCommandMetada Flow

### ISSUE THREAD

**Issue by mhertis** [d60/Cirqus#57]
Should `CurrentCommandMetada` flow between Aggregate Roots? AR `CurrentCommandMetadata` is set by `DefaultCommandContext`. If AR load/creates and invokes method on some other AR, `CurrentCommandMetadata` is not propagated.

I think this functionality needs to be added to the `AggregateRoot` `Load`, `TryLoad` anc `Create` implementation. 

https://github.com/d60/Cirqus/blob/master/d60.Cirqus/Commands/DefaultCommandContext.cs

**Comment by mookid8000** [comment]
Yes it should! I'll investigate when I get some time, maybe today or tomorrod

**Comment by mhertis** [comment]
I could try prepare a PR if needed.

**Comment by mookid8000** [comment]
That would be awesome!

-
Sendt fra min iPhone

**Comment by mookid8000** [comment]
Hi @mhertis , did you do anything about this? if not, I can take a look at it today...

**Comment by mhertis** [comment]
Unfortunately, I did not manage to find time.

**Comment by mookid8000** [comment]
excellent - I'll get right on it :)

**Comment by mookid8000** [comment]
Hmm, I don't seem to be able to reproduce the bug - if I understood the problem correctly, it was about metadata not flowing correctly to events emitted by other root instances that were created/loaded by an aggregate root?

Could you maybe take a look at the test I made to see which part of the problem I didn't nail correctly? I coded three test cases where the [`FlowsCorrectlyViaRootLoadingOtherRoot`](https://github.com/d60/Cirqus/blob/master/d60.Cirqus.Tests/Bugs/VerifyThatCommandMetadataFlowsToOtherRoots.cs#L65-L84) is my attempt at recreating your issue....

**Comment by mhertis** [comment]
Yes, that seems to be a problem. Will check it out, just a sec =D

**Comment by mookid8000** [comment]
ah, I extended the test case to use both `TestContext` and the real `CommandProcessor`  - I got an error with the real one, I'll investigate further :)

**Comment by mookid8000** [comment]
fixed it - waiting for the tests to pass and then 0.61.4 will be pushed to NuGet.org

**Comment by mookid8000** [comment]
@mhertis thanks for reporting the issue btw :+1:

**Comment by mhertis** [comment]
great, anytime =D
