### ISSUE TITLE
Do you have sample application that using your CQRS implementation?

### ISSUE THREAD

**Issue by thomas-tran** [d60/Cirqus#58]
Do you have sample application that using your CQRS implementation?

**Comment by mookid8000** [comment]
We have two rather silly sample projects in [the CirqusSamples repository](https://github.com/d60/CirqusSamples).

If you have any questions, please don't hesitate to ask them on StackOverflow - we promise to give quicks and thorough answers :)

**Comment by thomas-tran** [comment]
Hi,

Actually I am pretty new to this event sourcing. Your wiki contains very little information without high level architecture  and I am seeking for the tutorial explaining how to use your framework. I also would like to have the practical example how to use the pattern in production rather than experimental project and willing to contribute if you have one.

Regards
Thomas.

**Comment by asgerhallas** [comment]
It's unfortunate that there's no good sample project, but it takes a lot of time to make and maintain one. I wish I worked on a project, where I could open source the code, but I unfortunately I don't right now. But if I ever get an idea for such a project, I would :)

As for a service, that returns a view over orders (I my current work, it's projects though), I would - for a web api project - do something like this:

    public class ProjectsQueryController : ApiController
    {
        readonly IViewManager<ProjectsView> viewManager;

        public ProjectsQueryController(IViewManager<ProjectsView> viewManager)
        {
            this.viewManager = viewManager;
        }

        [Route("projects")]
        public async Task<ProjectsView> Get(string companyId, int? position = null)
        {
            return await viewManager.LoadView(companyId, position) ?? new ProjectsView();
        }
    }

Does that help, or did I misunderstand the question?

**Comment by thomas-tran** [comment]
That's why I am looking for but how do you implement the IViewManager?

**Comment by asgerhallas** [comment]
You don't have to, Cirqus comes with a few. In the entry point of your app, you can set it up like this:

    var ordersView = new MongoDbViewManager<OrdersView>("mongodb://localhost/sqlsug");

and then add the following line to the setup of the CommandProcessor:

    .EventDispatcher(e => e.UseViewManagerEventDispatcher(ordersView))

But that's actually included in the sqlsug demo here: https://github.com/d60/SqlsugCirqusDemo/blob/master/CirqusDemo/Program.cs

Does that help?

**Comment by thomas-tran** [comment]
Actually where is easy place to ask questions instead of raising an issue in github?  

I am wondering why and when to use the position?  

[Route("projects")]
public async Task<ProjectsView> Get(string companyId, int? position = null)
{
        return await viewManager.LoadView(companyId, position) ?? new ProjectsView();
}

**Comment by mookid8000** [comment]
Hi @thomas-tran - we prefer getting questions on StackOverflow :) you already [raised the question there](http://stackoverflow.com/questions/31601739/how-to-query-data-in-cqrs-cirqus), which is cool, so I'll give you an answer right away :+1:

**Comment by SamuelDebruyn** [comment]
I created [this one](https://github.com/SamuelDebruyn/AD5-Cirqus-demo). I'm going to give a quick demo of Cirqus to fellow students in a few months and that's why I had to create it. It's not complete, but it's enough for the demo (most students have just learned LINQ). Feel free to contribute :)
