### ISSUE TITLE
Logger in ViewManagerEventDispatcher is not changed

### ISSUE THREAD

**Issue by SamuelDebruyn** [d60/Cirqus#61]
I am building a project using dependency injection with Autofac and CQRS using Cirqus.

I built a *DebugLoggerFactory* and a *DebugLogger* which are exact copies of the *ConsoleLogger(Factory)*, but they log to *Debug* instead of to *Console* (my web project doesn't have a console).
*If you're interested in this, I'll submit a pull request with the debug logger.*

When I create a new aggregate root, my view is not updated. To further investigate this issue, I wanted to log everything that happens in the *ViewManagerEventDispatcher*. The problem is that the *ViewManagerEventDispatcher* still uses the *NullLogger* instead of the *DebugLogger* that is set in the *CommandProcessor*.
*This is what I noticed while debugging and looking at the static non-public members of the ViewManagerEventDispatcher in my ViewManager...*

This is how I initialize everything with *Autofac*:

```
            builder.RegisterInstance(new EntityFrameworkViewManager<SellerView>(_connectionStringName, false))
                    .AsSelf()
                    .As<IViewManager>();
            // add all views here (or find a better solution that automagically registers all views in our Views namespace ;) ), use .PreserveExistingDefaults() on every view except the first one

            builder.RegisterType<MsSqlEventStore>().WithParameters(new List<Parameter>
            {
                    new PositionalParameter(0, _connectionStringName),
                    new PositionalParameter(1, _eventsTableName)
            }).As<IEventStore>().SingleInstance();

            builder.RegisterType<DefaultDomainTypeNameMapper>().As<IDomainTypeNameMapper>();
            builder.RegisterType<JsonDomainEventSerializer>().As<IDomainEventSerializer>();
            builder.RegisterType<DefaultCommandMapper>().As<ICommandMapper>();
            builder.RegisterType<RealUnitOfWork>().As<IUnitOfWork>().InstancePerDependency();

            builder.RegisterType<DebugLoggerFactory>().As<CirqusLoggerFactory>();
            builder.RegisterType<Options>().PropertiesAutowired().AsSelf();

            builder.RegisterType<DefaultAggregateRootRepository>().As<IAggregateRootRepository>().SingleInstance();
            builder.RegisterType<ViewManagerEventDispatcher>().As<IEventDispatcher>().SingleInstance();
            builder.RegisterType<CommandProcessor>().As<ICommandProcessor>().SingleInstance();
```

The code above comes from a module that is being registered in the web API project that uses the class library which contains my CQRS code.

**Comment by mookid8000** [comment]
I think I know what's wrong :) Cirqus is meant to be configured using the fluent configuration API, which means that the prettiest way of registering the command processor in the container is to

* register all view managers as `IViewManager` instances
* register a singleton lifestyled factory for `ICommandProcessor` that resolves a command processor by calling the configuration API

E.g. with Autofac it could look like this:
```
builder.RegisterInstance<IViewManager>(new EntityFrameworkViewManager(...));
// .. add more view managers here

builder.Register(c => {
    var viewManagers = c.Resolve<IEnumerable<IViewManager>>().ToArray();

    var commandProcessor = CommandProcessor.With()
        .Logging(l => l.Use(new CirqusLoggerFactory())
        .EventStore(e => e.UseSqlServer(_connectionString, _eventsTableName))
        .EventDispatcher(e => e.UseViewManagerEventDispatcher(viewManagers))
        .Create();

    return commandProcessor;
})
.SingleInstance();
```

This is also much cleaner because your application container does not have to contain e.g. `IDomainTypeNameMapper` and other of Cirqus' internals.

I hope that makes sense ... please let me know if it doesn't work out for you :)

**Comment by SamuelDebruyn** [comment]
I also registered the ViewManagers `AsSelf` so that I could use them in my services to query them. How would you recommend querying an EntityFrameworkViewManager if I only have *IViewManagers* and a *CommandProcessor* available?

*Thanks for the quick reply, much appreciated!*

**Comment by mookid8000** [comment]
IMO it doesn't make sense to use Cirqus to query your views - as I see it, you use whichever type of view manager you've chosen _because you want the views to be in some particular place_, and you want to take advantage of the mechanisms and capabilities of that place to query your views.

In your case I would use EF to new up a context and grab an `IQueryable<YourView>` out of that, and then start querying :)

**Comment by mookid8000** [comment]
Btw I can recommend registering your view managers by doing something like this:

```
RegisterEfViewManager<FirstView>(builder, c => c.FirstViews);
RegisterEfViewManager<SecondView>(builder, c => c.SecondViews);
```

and then have `RegisterEfViewManager` do something like this:

```
void RegisterEfViewManager<TViewInstance>(ContainerBuilder builder, Func<EfContext, IQueryable<TViewInstance>> queryableResolver) 
    where TViewInstance : class, IViewInstance, ISubscribeTo, new()
{
    var viewManager = new EntityFrameworkViewManager<TViewInstance>();
    builder.RegisterInstance<IViewManager>(viewManager);

    builder.Register(c => {
        var context = c.Resolve<EfContext>();

        return queryableResolver(context);
    });
}
```

provided that you have created an EF context named `EfContext` whose lifestyle is properly managed (i.e. probably tied to the web request or something)

This way, your API controllers can be pretty and persistence ignorant and just have `IQueryable<SomeView>` injected.

**Comment by SamuelDebruyn** [comment]
The method `Logging()` after the `With()` returns a different object than the `With()` method. The method `EventStore()` is therefore not found...
When I remove the line with `Logging()`, it builds fine.

Also: do I still need to call `Initialize()` after initializing the processor this way?

Another question: so why would I use EF ViewManager instead of SQL Server ViewManager if I still have to create a new DbContext myself and query the database? What is the (dis)advantage of the EF ViewManager?

**Comment by SamuelDebruyn** [comment]
Yet another question... :) It seems like I need a *RealUnitOfWork* to perform `Get` operations. Its constructor needs a repository and a domainTypeMapper. Can I get the repository from the *CommandProcessor* in any way so I don't have to create a new one?

**Comment by mookid8000** [comment]
`MsSqlViewManager` is very simple because it uses one single table to store its view instances (although you _can_ store "rich" objects by applying the `[Json]` attribute to a view property, which will JSON-serialize the object into a single column).

The advantage of the EF view manager is that it can be used to persist your view even though it might contain collection of other things - EF will then use several tables to store one single view.

**Comment by mookid8000** [comment]
If you use the configuration API, the `ICommandProcessor` is ready-to-use when you've called `Create()` - this means that everything that needs initialization has been initialized.

**Comment by mookid8000** [comment]
`RealUnitOfWork` is an implementation detail inside Cirqus - it's unlikely that you'll ever need to work with it directly :)

**Comment by mookid8000** [comment]
With Cirqus, a command is a unit of work - i.e. either it gets processed and succeeds in saving a batch of events to the event store, or it doesn't.

**Comment by SamuelDebruyn** [comment]
So I shouldn't use Cirqus to retrieve any data? At the moment, I use `Get` to retrieve a single Aggregate Root with all its details that aren't always stored in a view.

PS: Any idea on the issue with `Logging()`?

**Comment by mookid8000** [comment]
Aggregate roots will be hydrated as needed when you execute a command.

E.g. you can derive your own command from `Command<SomeRoot>` which will create/update a single aggregate root instance, or you can derive your command from `ExecutableCommand` and use the `ICommandContext` to `Create`, `Load`, and `TryLoad` as many instances as you like.

Ultimately all commands are derived off of the base `Command`, but that one requires that you manually map each command type to a function (which has been automagically done for you when you use the generic `Command<TRoot>` and `ExecutableCommand`).

**Comment by mookid8000** [comment]
Regarding "the missing `.EventStore(..)` method" - could you paste your configuration here? I'm pretty sure the method is there.... :smiley:

**Comment by SamuelDebruyn** [comment]
It's the one you posted as the first answer:

```
                var commandProcessor = CommandProcessor
                    .With()
                    .Logging(l => l.Use(new DebugLoggerFactory())
                    .EventStore(e => e.UseSqlServer(_connectionStringName, _eventsTableName))
                    .EventDispatcher(e => e.UseViewManagerEventDispatcher(viewManagers))
                    .Create();

                return commandProcessor;
            }).SingleInstance();
```

This is `DebugLoggerFactory`:
```
    public class DebugLoggerFactory: CirqusLoggerFactory
    {
        private readonly Logger.Level _minLevel;

        public DebugLoggerFactory(Logger.Level minLevel = Logger.Level.Debug)
        {
            _minLevel = minLevel;
        }

        public override Logger GetLogger(Type ownerType)
        {
            return new DebugLogger(ownerType, _minLevel);
        }
    }
```

The errors:
* https://onedrive.live.com/redir?resid=B5240A36EC9AE039!292199&authkey=!ABLSIZPkzO5qjPk&ithint=file%2cPNG
* https://onedrive.live.com/redir?resid=B5240A36EC9AE039!292200&authkey=!AEv0MFJ74V-V9TQ&ithint=file%2cPNG

**Comment by mookid8000** [comment]
looks weird - on my machine, R# sometimes goes nuts and puts red squigglies allover, but it usually helps to reload the solution.... sometimes I need to restart VS though.. could you try that?

**Comment by mookid8000** [comment]
BTW a pull request with your `DebugLoggerFactory` would be most welcome :)

**Comment by SamuelDebruyn** [comment]
My mistake, forgot a bracket...

**Comment by SamuelDebruyn** [comment]
Your method to register EfViewManagers just misses a connectionString in `var viewManager = new EntityFrameworkViewManager<TViewInstance>();` which you can add as a parameter :)

**Comment by SamuelDebruyn** [comment]
I've setup the autofac registration with your examples, but now the viewmanager doesn't create new tables and throws exceptions like `2015-08-24T15:30:13.5110343+02:00|Warn|d60.Cirqus.Views.ViewManagerEventDispatcher|Could not catch up - waiting 00:00:01 - exception: System.AggregateException: One or more errors occured. ---> System.Data.Entity.Core.EntityCommandExecutionException: An error occurred while executing the command definition. See the inner exception for details. ---> System.Data.SqlClient.SqlException: Invalid object name 'dbo.SellerView_Position'.`

`SellerView` is the name of my view...

**Comment by mookid8000** [comment]
hmm, I'm not an expert on EF.... I think you need to create a `DbContext` that has properties that reference your view types, e.g. something like this:

```
public class CirqusViewsDbContext : DbContext
{
    public IDbSet<SellerView> SellerViews { get; set; }
}
```
and then somehow kick EF until it performs an auto-migration of your database schema.... I think you do that by creating all kinds of silly derived configuration classes which you pass to a static method somewhere, something like
```
Database.SetInitializer(new SomeKindOfInitializer<CirqusViewsDbContext>());
```
but I don't remember which initializer works. But iirc this will make EF run some kind of schema migration when you first new up your `CirqusViewsDbContext`.

The EF migration API is so terrible that the few times I've worked with Entity Framework, I've manually migrated my database with [migr8](https://www.nuget.org/packages/Migr8/).

**Comment by SamuelDebruyn** [comment]
That's already the case. But the creation of the tables should happen in `EntityFrameworkViewManager`, no?

**Comment by mookid8000** [comment]
that's no longer the intention

it used to be, but I vaguely recall being unable to package it up nicely

**Comment by SamuelDebruyn** [comment]
So I have to create a table for every view myself and another one called MyView_Position? What was the schema of the Position table?

(I'm sorry for all the questions, I'll try to improve the docs when I fully understand how Cirqus works.)

**Comment by mookid8000** [comment]
you know what, forget what I said before - `EntityFrameworkViewManager` should create the tables by itself! just a moment, I'll take a look...

**Comment by SamuelDebruyn** [comment]
(If you want to take a look at my code, hit me up on Skype: samuel.debruyn. I'm available until 17h30 GMT+2, 15h30 UTC)

**Comment by mookid8000** [comment]
check out [the constructor of `EntityFrameworkViewManager`](https://github.com/d60/Cirqus/blob/master/d60.Cirqus.EntityFramework/EntityFrameworkViewManager.cs#L20-L36) - it should create the necessary tables by itself, unless you explicitly disable this feature

have you tried configuring everything and then starting it up on a clean database? (i.e. without the __MigrationHistory table)

**Comment by SamuelDebruyn** [comment]
Yes, I created a new database on LocalDB and changed my connection string to that DB.

**Comment by mookid8000** [comment]
weird - I'm sorry, but I have to shut down my computer now .... I'll be happy to help you make this work, but I would have to be tomorrow...

**Comment by SamuelDebruyn** [comment]
No problem, I'll be back at 7h30 UTC :) Thanks for all the help, I really appreciate it! I looked at several possible ways to implement CQRS in a .NET application and Cirqus seemed to be the best solution, great work!
