### ISSUE TITLE
Wiki collaboration

### ISSUE THREAD

**Issue by SamuelDebruyn** [d60/Cirqus#70]
I'm going to write a lot of documentation on Cirqus but I can't push my changes to the wiki. I created a fork at https://github.com/SamuelDebruyn/Cirqus.Wiki-fork

Is it possible to change the wiki collaboration setting so everyone can contribute?

**Comment by mookid8000** [comment]
The settings already look like this:

![skaermbillede 2015-11-23 kl 09 23 18](https://cloud.githubusercontent.com/assets/32968/11332204/e1f03e6c-91c3-11e5-9798-e9abf266affe.png)

Do you know if there's some other setting I need to change?

**Comment by SamuelDebruyn** [comment]
That should be fine, I probably did something wrong when pushing my commits. Thanks for the quick reply!

**Comment by mookid8000** [comment]
No, thank _you_ :smiley: It's so cool that you're doing this :+1:

**Comment by SamuelDebruyn** [comment]
You're welcome :smile: 
Most of the documentation should be finished by the end of this year.
As it's impossible to comment on my changes etc. I created [a fork](https://github.com/SamuelDebruyn/Cirqus.Wiki-fork/commits/master) which is automatically updated with the latest commits to the wiki every hour.
Feel free to comment on the commits over there if you have feedback :wink:

**Comment by mookid8000** [comment]
I read your initial edits - you are really good at explaining things!
