### ISSUE TITLE
Add name of class to exception message on failed method lookup with reflection

### ISSUE THREAD

**Issue by mortenhm** [d60/Cirqus#72]
ApplyEvent method of AggregateRoot class throws an exception when failing to locate Apply method on the concrete root class. This exception (and maybe others of same type) could include information about which concrete root class was reflected. 

Small change I think, but the information could probably have saved me a few days of debugging a copy paste error.

https://github.com/d60/Cirqus/blob/c7f0a638ab447224e2529a2a723c81c8312d2111/d60.Cirqus/Aggregates/AggregateRoot.cs#L135

**Comment by mookid8000** [comment]
Great idea :+1:

**Comment by mookid8000** [comment]
it'll be out in 0.66.2 in a few minutes - thanks for the suggestion :)

**Comment by mortenhm** [comment]
Thanks! :)
