### ISSUE TITLE
Could not update HybridDB to 0.10.0

### ISSUE THREAD

**Issue by mookid8000** [d60/Cirqus#74]
Updated the HybridDB dependency to 0.10.0 and corrected the configuration action, and then I got this when running a test:

    System.Data.SqlClient.SqlException : Invalid object name 'HeaderCounter_HybridDb'.
      at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
      (...)
      at Dapper.SqlMapper.QueryMultiple(IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Nullable`1 commandTimeout, Nullable`1 commandType) in c:\Dev\Dapper\Dapper NET40\SqlMapper.cs:line 836
      at HybridDb.DocumentStore.InternalQuery[T](ManagedConnection connection, SqlBuilder sql, Object parameters, QueryStats& stats) in c:\workspace\HybridDb\src\HybridDb\DocumentStore.cs:line 290
      at HybridDb.DocumentStore.Query[TProjection](DocumentTable table, QueryStats& stats, String select, String where, Int32 skip, Int32 take, String orderby, Object parameters) in c:\workspace\HybridDb\src\HybridDb\DocumentStore.cs:line 230
      at d60.Cirqus.HybridDb.HybridDbViewManager`1.Purge() in C:\Projects\Cirqus\d60.Cirqus.HybridDb\HybridDbViewManager.cs:line 116

It happens in the `Purge()` method of the HybridDbViewManager, where it seems its way of manually building a bunch of delete commands in order to clear the existing data trips over the fact that the table does not exist (yet?).

Should this exception just be ignored? Or is there a way to be sure that the schema is in place in the purge method?

**Comment by mookid8000** [comment]
@asgerhallas do you know?

**Comment by asgerhallas** [comment]
@mookid8000 very interested! I'll look at it right away! :)

**Comment by asgerhallas** [comment]
@mookid8000 are you sure you pushed? It says that branch is even with master - and all tests are running on my end :)

**Comment by asgerhallas** [comment]
@mookid8000 I have updated it and replicated the issue, I'm on it :)

**Comment by mookid8000** [comment]
you rock :metal:

**Comment by asgerhallas** [comment]
@mookid8000 the tests are running now :)

There are a few changes to the setup of HybridDb, that needs attention in client applications. The motivation for the changes is actually easier use in Cirqus:

1. The DocumentStore must be initialized (call store.Initialize()) before being used. That makes it easier to configure the store in multiple places and have the initialization process run after that. We could for example let the HybridDbViewManager configure it's own internal ViewPositions table, so the client doesn't have to do it.
2. You don't have to setup documents, that do not have any projections... they will all just be persisted to a base Documents table. That is of course in preparation for ad hoc indexes using JSON/XML columns :) But it also means that you can persist any object at any time - for example anonymous objects.
3. Last thing to know, is that I finally gave in and used a default of full .NET type name as discriminator. That can be changed by registering a custom TypeMapper in the setup.
4. Configuration can be done on DocumentStore.Create by passing a lambda or by using store.Configuration.Document() and so on before calling store.Initialize().

**Comment by mookid8000** [comment]
is it merged into master?

**Comment by asgerhallas** [comment]
No, sorry, I didn't get around to that...

Sent from my phone

On 6. apr. 2016, at 13.37, Mogens Heller Grabe <notifications@github.com<mailto:notifications@github.com>> wrote:


is it merged into master?

**Comment by mookid8000** [comment]
I'll do it! 👍

**Comment by mookid8000** [comment]
new Cirqus with updated HybridDB dependency (0.10.0) is out in 0.67.0 on Nuget.org now! 😁

**Comment by mookid8000** [comment]
out in 0.67.0 now 😃
