### ISSUE TITLE
how does this differ from datomic?

### ISSUE THREAD

**Issue by whatsdis** [d60/Cirqus#77]
should I use this or datomic?

**Comment by mookid8000** [comment]
Use whichever fits your needs best.

Cirqus is an event sourcing and CQRS framework for .NET where [certain choices have been made regarding which quality attributes to accentuate](https://github.com/d60/Cirqus#is-cirqus-for-you). This may or may not align with what you need.

I suggest you read [the README](https://github.com/d60/Cirqus/blob/master/README.md) and maybe [take the samples for a spin](https://github.com/d60/CirqusSamples). Feel free to ask any concrete questions regarding Cirqus [on StackOverflow](http://stackoverflow.com/questions/tagged/cirqus) (remember the 'cirqus' tag).
