### ISSUE TITLE
how to use this with datomic?

### ISSUE THREAD

**Issue by whatsdis** [d60/Cirqus#78]
how can you integrate this with datomic and other azure services to put cirqus in the cloud? also is anyone using cirqus in production?

**Comment by mookid8000** [comment]
There no integration with Datomic at the moment.

You can definitely put Cirqus in the cloud, e.g. using SQL Azure as both event store and views database.

And yes, at [d60](http://www.d60.dk/) we have a couple of solutions built on Cirqus where especially one of them is pretty interesting: It has a central event store on a SQL Server instance placed at the customer's hosting center in Denmark, and then it hosts an instance of the system on Azure in Amsterdam that builds its views from that event store. In addition to this, it replicates events to additional locations around the world where instances of the system build their views from replicated events and keep local view databases up-to-date. Pretty sleek 😄
