### ISSUE TITLE
Upgrading events

### ISSUE THREAD

**Issue by kimbirkelund** [d60/Cirqus#79]
We have a case where we want to change how an event looks, or more exactly create a new version of an event that already exists. E.g. an update event that in the future should contain more data. 

Obviously we cannot change the events that already exists, but also we don't want to keep having to handle old versions of the event in new views.

To support this we decorate the domain event serializer and in the Deserialize method we upgrade the event (i.e. replace it with another instance of the new type) prior to returning it. 

Upgrading to 0.66.1 this breaks in some scenarios (granted some weird scenarios only exposed by tests) because the serialization steps is skipped for new events. As mentioned this isn't really an issue as upgrading newly emitted events is a bit weird for other than test purposes.

What I want to know is this: where in the design would a feature like this naturally live in your opinion?

If we can agree on the location and design I'll make a pull request once we've matured the implementation a bit on our side.

**Comment by mookid8000** [comment]
We have at least one system running with "on-the-fly event migrations" at the moment, where we have decorated `IEventStore` to run a pipeline of migrations for events in their `EventData` form before they are returned.

Migrating events in this case consists of turning them into `JObject`s, which we then gently nudge into place, and then we convert them back into a `byte[]` again.

The individual migrations then use `Meta` do determine whether it makes sense to go through the hassle, because obviously this has performance implications.... but so far we have been able to do fine with them 😄 

Once they become a problem we will write a one-off job that uses `EventReplicator` to convert the events into their new format, and then we can start over... (keeping a backup of the old event store, of course 😁)

**Comment by kimbirkelund** [comment]
I opted for not using that approach to avoid working with EventData. 

I wonder how much you actually save though, as instead of deserializing an event that'll be replaced by another object you deserialize and serialize instead (albeit only to JObject). 

But if I'm not mistaken it doesn't get around the issue introduced, in 0.66.1, by skipping the serialization step in the dispatcher? (again that really is a non-issue)

**Comment by mookid8000** [comment]
> I wonder how much you actually save though, as instead of deserializing an event that'll be replaced by another object you deserialize and serialize instead (albeit only to JObject).

My guess, based on my own experiences, is that the hit will be negligible in most scenarios. But then again, we are not in a performance-critical world, so ymmv.

Of course, if you have HUGE events, then there will be a lot of `byte[]` churn. We did ensure, however, that events were turned into `JObject` once, which the pipeline could then work on without serializing back and forth, and then only converting back to `byte[]` at the end.

**Comment by mookid8000** [comment]
> But if I'm not mistaken it doesn't get around the issue introduced, in 0.66.1, by skipping the serialization step in the dispatcher? (again that really is a non-issue)

In this because you rely on being able to mutate newly emitted events? Because yes, then decorating `IEventStore` will not make it work either.

**Comment by kimbirkelund** [comment]
We had a test that relied on upgrading newly emitted events. So changing that fixed the issue.

For now we'll stick with our current implementation.

This issue was mostly evaluating whether it made sense to develop this into a feature I could pull-request back into Cirqus.

**Comment by mookid8000** [comment]
ah, now I get it 😄 well in that case I don't think it makes that much sense

**Comment by kimbirkelund** [comment]
Fair enough :)

**Comment by mookid8000** [comment]
(if you felt strongly about it, I am sure you would have tried to convince me by now)

**Comment by kimbirkelund** [comment]
:)
