### ISSUE TITLE
How to build a microservices like architecture

### ISSUE THREAD

**Issue by NKnusperer** [d60/Cirqus#83]
For the purpose of learning Cirqus I created a simple banking app which basically looks like this:
AggregateRoot: BankAccount
Commands: CreateBankAccount, PerformDeposit, PerformWithdrawal
Events: BankAccountCreated, DepositPerformed, WithdrawalPerformed

While this all works fine in a standalone app I'am wondering how you would use this from the outside, e.g. another process on another machine.

Lets say there is a shopping app and we want to withdrawal money from the customer to shop.
Obviously I cannot simply send a PerformWithdrawal command because 1) I would pull in all dependencies down to the AggregateRoot from the banking app but even worst 2) I might want to do some additional validation before actually sending the money (does the customer even has a bank account?).

So the question is how to design this banking thingy to be usable from the outside without actually having a dependency on it?
Maybe you would first send something like a CanPerformWithdrawal command?
And if yes how to wire this up?

Another use case would be to have statistics which would basically just a bunch of Views showing how many transaction were made every day or so.
Obviously I don't want to bake this into the core banking app, it should be his own Independent service.

I guess that I'am missing some important conceptual point so please enlighten me.

**Comment by NKnusperer** [comment]
After some more research it looks like Cirqus is not really designed to supported this kind of distributed scenario.  However you guys seems to be also the developers of rebus, so this might be the solution?
Multiple services are using Cirqus for their stuff internally and expose there functionality via rebus?

**Comment by mookid8000** [comment]
@NKnusperer sorry for not answering your first question – I read it on my phone and wanted to post a good answer when I came by a computer, but I forgot about it 😁 

But yet – my answer would basically just say something along the lines of the conclusion that you came to on your own – Cirqus is not really meant to be used _across_ "services" (or whatever you call it....)

Cirqus is meant to work as an application framework within a single application, which just happens to make it easy to add integrations by reacting to events – most likely by re-publishing these events via [some kind of durable pub/sub mechanism](https://github.com/rebus-org/Rebus).
