### ISSUE TITLE
Q: .net core compatibility?

### ISSUE THREAD

**Issue by kri5t** [d60/Cirqus#86]
Is this project still being maintained. As I can see the last update was 7 months ago.
I wanted to know if it is going to be ported to .netcore anytime in the future?

**Comment by mookid8000** [comment]
It's still being maintained as in: We (d60) use it for a couple of applications, and we fix issues if we find any 😄 

But unfortunately we are not currently planning porting it to .NET Core, as it's not currently a thing that we need.

**Comment by pvivera** [comment]
FYI 2 months ago I started to port it to .netstandard but 1.6 doesn't have binary serialization. The Core team is going to add it in 2.0 so as soon they release it I'll finish the base part of Cirqus with MSSQL support.

**Comment by NKnusperer** [comment]
@pvivera have you tried v2.0 preview build from [dotnet/cli](/dotnet/cli) ?
Would be interesting to know if stuff might be already working.

**Comment by pvivera** [comment]
@NKnusperer I didn't test it yet. I'll keep you posted.

**Comment by pvivera** [comment]
@NKnusperer I've completed the migration to netstandard2.0 using dotnet 2.0.0-preview2-006497 and Visual Studio 2017 Preview.

All projects are targeting net45 and netstandard2.0 except d60.Cirqus.EntityFramework and d60.Cirqus.HybridDb.

The work lives at netstandard branch in my fork.

```
λ dotnet test -f netcoreapp2.0 -v q /property:Platform=X64
Build started, please wait...
Build completed.

Test run for C:\dev\Cirqus\new\test\d60.Cirqus.Tests\bin\X64\Debug\netcoreapp2.0\d60.Cirqus.Tests.dll(.NETCoreApp,Version=v2.0)
Microsoft (R) Test Execution Command Line Tool Version 15.3.0-dev
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
NUnit Adapter 3.8.0.0: Test execution started
Running all tests in C:\dev\Cirqus\new\test\d60.Cirqus.Tests\bin\X64\Debug\netcoreapp2.0\d60.Cirqus.Tests.dll
NUnit3TestExecutor converted 473 of 473 NUnit test cases
NUnit Adapter 3.8.0.0: Test execution complete

Total tests: 473. Passed: 406. Failed: 0. Skipped: 67.
Test Run Successful.
Test execution time: 2.8068 Minutes
```

```
λ dotnet test -f net45 -v q /property:Platform=X64
Build started, please wait...
Build completed.

Test run for C:\dev\Cirqus\new\test\d60.Cirqus.Tests\bin\X64\Debug\net45\d60.Cirqus.Tests.dll(.NETFramework,Version=v4.5)
Microsoft (R) Test Execution Command Line Tool Version 15.3.0-dev
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
NUnit Adapter 3.8.0.0: Test execution started
Running all tests in C:\dev\Cirqus\new\test\d60.Cirqus.Tests\bin\X64\Debug\net45\d60.Cirqus.Tests.dll
NUnit3TestExecutor converted 494 of 494 NUnit test cases
NUnit Adapter 3.8.0.0: Test execution complete

Total tests: 494. Passed: 420. Failed: 0. Skipped: 74.
Test Run Successful.
Test execution time: 3.0778 Minutes
```

**Comment by brettwinters** [comment]
Hi @pvivera - I can't find the netstandard branch in your fork. Is it [this one](https://github.com/pvivera/Cirqus)
