### ISSUE TITLE
Required default constructor on aggregate roots

### ISSUE THREAD

**Issue by kimbirkelund** [d60/Cirqus#90]
We've run into a situation where we want to use the factory method support for creating aggregate roots, to inject some dependencies. However the fact that Command<T> requires the root to have a default constructor means we need to keep it around even though we don't want to use it.

How easy would it be to remove that restriction? As far as I can tell other parts of the system doesn't require it.

**Comment by mookid8000** [comment]
I have no idea :) isn't the constraint only a requirement if you derive commands from `Command<TAggregateRoot>`?

If I were you, I would fork the code and try and play around with it.
